### ISSUE TITLE
[PE-D] UG clear command slightly confusing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-1/tp#197]
![UG confusing clear command.png](https://raw.githubusercontent.com/sj1999-BIT/ped/main/files/9c075069-927e-40ad-b20c-98f1de17232c.png)

A bit more serious.

I understand that you have already stated that clearm will clear all the members.
However, because of the cleara command, its could potential lead to serious problems as the two commands are so similar in terms of syntax.
 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: sj1999-BIT/ped#2

**Comment by Shruthi0310** [comment]
This one no need to change right since we gave a warning already.

**Comment by Moley456** [comment]
> This one no need to change right since we gave a warning already.

Yeah I don't think we need to change, or rather not sure how to change also. Best thing we could have done was to have confirmation by the user but I don't think we're allowed to do that anymore
